const List surah = [
  {
    "id": 1,
    "name": "Al Fatiha",
    "aya": 7,
    "english": "The Opening",
    "turkish": "Fâtiha",
    "french": "L'ouverture",
    "place": "Makkah",
    "arabic": "الفاتحة",
    "russian": "Открывающая Коран",
  },
  {
    "id": 2,
    "name": "Al Baqarah",
    "aya": 286,
    "english": "The Cow",
    "turkish": "Bakara",
    "french": "La Vache",
    "place": "Madinah",
    "arabic": "البقرة",
    "russian": "Корова",
  },
  {
    "id": 3,
    "name": "Al Imran",
    "aya": 200,
    "english": "The Family of Imran",
    "turkish": "Âl-i İmrân",
    "french": "La famille D'Imran",
    "place": "Madinah",
    "arabic": "آل عمران",
    "russian": "Семейство Имрана",
  },
  {
    "id": 4,
    "name": "An Nisa",
    "aya": 176,
    "english": "The Women",
    "turkish": "Nisâ",
    "french": "Les femmes",
    "place": "Madinah",
    "arabic": "النساء",
    "russian": "Женщины",
  },
  {
    "id": 5,
    "name": "Al Ma'idah",
    "aya": 120,
    "english": "The Table",
    "turkish": "Mâide",
    "french": "La table servie",
    "place": "Madinah",
    "arabic": "المائدة",
    "russian": "Трапеза",
  },
  {
    "id": 6,
    "name": "Al An'am",
    "aya": 165,
    "english": "The Cattle",
    "turkish": "En'âm",
    "french": "Les bestiaux",
    "place": "Makkah",
    "arabic": "الأنعام",
    "russian": "Скот",
  },
  {
    "id": 7,
    "name": "Al A'raf",
    "aya": 206,
    "english": "The Heights",
    "turkish": "A'râf",
    "french": "Les murailles",
    "place": "Makkah",
    "arabic": "الأعراف",
    "russian": "Ограды",
  },
  {
    "id": 8,
    "name": "Al Anfal",
    "aya": 75,
    "english": "The Spoils of War",
    "turkish": "Enfâl",
    "french": "Le butin",
    "place": "Madinah",
    "arabic": "الأنفال",
    "russian": "Трофеи",
  },
  {
    "id": 9,
    "name": "At Tawbah",
    "aya": 129,
    "english": "The Repentance",
    "turkish": "Tevbe",
    "french": "Le repentir",
    "place": "Madinah",
    "arabic": "التوبة",
    "russian": "Покаяние",
  },
  {
    "id": 10,
    "name": "Al Yunus",
    "aya": 109,
    "english": "Jonah",
    "turkish": "Yûnus",
    "french": "Jonas",
    "place": "Makkah",
    "arabic": "يونس",
    "russian": "Иона",
  },
  {
    "id": 11,
    "name": "Hud",
    "aya": 123,
    "english": "Hud",
    "turkish": "Hûd",
    "french": "Hud",
    "place": "Makkah",
    "arabic": "هود",
    "russian": "Худ",
  },
  {
    "id": 12,
    "name": "Yusuf",
    "aya": 111,
    "english": "Joseph",
    "turkish": "Yûsuf",
    "french": "Joseph",
    "place": "Makkah",
    "arabic": "يوسف",
    "russian": "Иосиф",
  },
  {
    "id": 13,
    "name": "Ar Ra'd",
    "aya": 43,
    "english": "The Thunder",
    "turkish": "Ra'd",
    "french": "Le tonnerre",
    "place": "Madinah",
    "arabic": "الرعد",
    "russian": "Гром",
  },
  {
    "id": 14,
    "name": "Ibrahim",
    "aya": 52,
    "english": "Abraham",
    "turkish": "İbrâhîm",
    "french": "Abraham",
    "place": "Makkah",
    "arabic": "ابراهيم",
    "russian": "Авраам",
  },
  {
    "id": 15,
    "name": "Al Hijr",
    "aya": 99,
    "english": "The Stoneland",
    "turkish": "Hicr",
    "french": "Le chemin rocailleux",
    "place": "Makkah",
    "arabic": "الحجر",
    "russian": "Хиджр",
  },
  {
    "id": 16,
    "name": "An Nahl",
    "aya": 128,
    "english": "The Honey Bee",
    "turkish": "Nahl",
    "french": "Les abeilles",
    "place": "Makkah",
    "arabic": "النحل",
    "russian": "Пчёлы",
  },
  {
    "id": 17,
    "name": "Al Isra'",
    "aya": 111,
    "english": "The Night Journey",
    "turkish": "İsrâ",
    "french": "Le voyage nocturne",
    "place": "Makkah",
    "arabic": "الإسراء",
    "russian": "Ночной перенос",
  },
  {
    "id": 18,
    "name": "Al Kahf",
    "aya": 110,
    "english": "The Cave",
    "turkish": "Kehf",
    "french": "La caverne",
    "place": "Makkah",
    "arabic": "الكهف",
    "russian": "Пещера",
  },
  {
    "id": 19,
    "name": "Maryam",
    "aya": 98,
    "english": "Mary",
    "turkish": "Meryem",
    "french": "Marie",
    "place": "Makkah",
    "arabic": "مريم",
    "russian": "Мария",
  },
  {
    "id": 20,
    "name": "Ta Ha",
    "aya": 135,
    "english": "Ta Ha",
    "turkish": "Tâhâ",
    "french": "Ta-Ha",
    "place": "Makkah",
    "arabic": "طه",
    "russian": "Та Ха",
  },
  {
    "id": 21,
    "name": "Al Anbiya",
    "aya": 112,
    "english": "The Prophets",
    "turkish": "Enbiyâ",
    "french": "Les prophètes",
    "place": "Makkah",
    "arabic": "الأنبياء",
    "russian": "Пророки",
  },
  {
    "id": 22,
    "name": "Al Hajj",
    "aya": 78,
    "english": "The Pilgrimage",
    "turkish": "Hac",
    "french": "Le pèlerinage",
    "place": "Madinah",
    "arabic": "الحج",
    "russian": "Паломничество",
  },
  {
    "id": 23,
    "name": "Al Mu minun",
    "aya": 118,
    "english": "The Believers",
    "turkish": "Mü'minûn",
    "french": "Les croyants",
    "place": "Makkah",
    "arabic": "المؤمنون",
    "russian": "Верующие",
  },
  {
    "id": 24,
    "name": "An Nur",
    "aya": 64,
    "english": "The Light",
    "turkish": "Nûr",
    "french": "La lumière",
    "place": "Madinah",
    "arabic": "النور",
    "russian": "Свет",
  },
  {
    "id": 25,
    "name": "Al Furqan",
    "aya": 77,
    "english": "The Criterion",
    "turkish": "Furkân",
    "french": "Le discernement",
    "place": "Makkah",
    "arabic": "الفرقان",
    "russian": "Различение",
  },
  {
    "id": 26,
    "name": "As Su'ara",
    "aya": 227,
    "english": "The Poets",
    "turkish": "Şuarâ",
    "french": "Les poètes",
    "place": "Makkah",
    "arabic": "الشعراء",
    "russian": "Поэты",
  },
  {
    "id": 27,
    "name": "An Naml",
    "aya": 93,
    "english": "The Ant",
    "french": "Les fourmis",
    "turkish": "Neml",
    "place": "Makkah",
    "arabic": "النمل",
    "russian": "Муравьи",
  },
  {
    "id": 28,
    "name": "Al Qasas",
    "aya": 88,
    "english": "The Narrations",
    "turkish": "Kasas",
    "french": "Le récit",
    "place": "Makkah",
    "arabic": "القصص",
    "russian": "Рассказ",
  },
  {
    "id": 29,
    "name": "Al Ankabut",
    "aya": 69,
    "english": "The Spider",
    "turkish": "Ankebût",
    "french": "L'araignée",
    "place": "Makkah",
    "arabic": "العنكبوت",
    "russian": "Паук",
  },
  {
    "id": 30,
    "name": "Ar Rum",
    "aya": 60,
    "english": "Rome",
    "turkish": "Rûm",
    "french": "Les romains",
    "place": "Makkah",
    "arabic": "الروم",
    "russian": "Римляне",
  },
  {
    "id": 31,
    "name": "Luqman",
    "aya": 34,
    "english": "Luqman",
    "turkish": "Lokmân",
    "french": "Luqman",
    "place": "Makkah",
    "arabic": "لقمان",
    "russian": "Лукман",
  },
  {
    "id": 32,
    "name": "As Sajdah",
    "aya": 30,
    "english": "The Prostration",
    "turkish": "Secde",
    "french": "La prosternation",
    "place": "Makkah",
    "arabic": "السجدة",
    "russian": "Земной поклон",
  },
  {
    "id": 33,
    "name": "Al Ahzab",
    "aya": 73,
    "english": "The Clans",
    "turkish": "Ahzâb",
    "french": "Les coalisés",
    "place": "Madinah",
    "arabic": "الأحزاب",
    "russian": "Союзники",
  },
  {
    "id": 34,
    "name": "Saba'",
    "aya": 54,
    "english": "Sheba",
    "turkish": "Sebe'",
    "french": "Saba",
    "place": "Makkah",
    "arabic": "سبإ",
    "russian": "Сава",
  },
  {
    "id": 35,
    "name": "Fatir",
    "aya": 45,
    "english": "The Originator",
    "turkish": "Fâtır",
    "french": "Le créateur",
    "place": "Makkah",
    "arabic": "فاطر",
    "russian": "Творец",
  },
  {
    "id": 36,
    "name": "Ya'sin",
    "aya": 83,
    "english": "Ya Sin",
    "turkish": "Yâsîn",
    "french": "Ya Sin",
    "place": "Makkah",
    "arabic": "يس",
    "russian": "Йа Син",
  },
  {
    "id": 37,
    "name": "As Saffat",
    "aya": 182,
    "english": "Those Who Set The Ranks",
    "turkish": "Sâffât",
    "french": "Les rangées",
    "place": "Makkah",
    "arabic": "الصافات",
    "russian": "Выстроившиеся в ряды",
  },
  {
    "id": 38,
    "name": "Saad",
    "aya": 88,
    "english": "Ṣād",
    "turkish": "Sâd",
    "french": "Ṣād",
    "place": "Makkah",
    "arabic": "ص",
    "russian": "Сад",
  },
  {
    "id": 39,
    "name": "Az Zumar",
    "aya": 75,
    "english": "The Crowds",
    "turkish": "Zümer",
    "french": "Les groupes",
    "place": "Makkah",
    "arabic": "الزمر",
    "russian": "Толпы",
  },
  {
    "id": 40,
    "name": "Ghafir",
    "aya": 85,
    "english": "The Forgiver",
    "turkish": "Mü'min",
    "french": "Le pardonneur",
    "place": "Makkah",
    "arabic": "غافر",
    "russian": "Прощающий",
  },
  {
    "id": 41,
    "name": "Fussilat",
    "aya": 54,
    "english": "Expounded",
    "turkish": "Fussilet",
    "french": "Les versets détaillés",
    "place": "Makkah",
    "arabic": "فصلت",
    "russian": "Разъяснены",
  },
  {
    "id": 42,
    "name": "As Sura",
    "aya": 53,
    "english": "The Consultation",
    "turkish": "Şûrâ",
    "french": "La consultation",
    "place": "Makkah",
    "arabic": "الشورى",
    "russian": "Совет",
  },
  {
    "id": 43,
    "name": "Az Zukhruf",
    "aya": 89,
    "english": "The Gold Adornments",
    "turkish": "Zuhruf",
    "french": "L'ornement",
    "place": "Makkah",
    "arabic": "الزخرف",
    "russian": "Украшения",
  },
  {
    "id": 44,
    "name": "Ad Dukhan",
    "aya": 59,
    "english": "The Smoke",
    "turkish": "Duhân",
    "french": "La fumée",
    "place": "Makkah",
    "arabic": "الدخان",
    "russian": "Дым",
  },
  {
    "id": 45,
    "name": "Al Jaathiyah",
    "aya": 37,
    "english": "The Kneeling Down",
    "turkish": "Câsiye",
    "french": "L'agenouillée",
    "place": "Makkah",
    "arabic": "الجاثية",
    "russian": "Коленопреклонённые",
  },
  {
    "id": 46,
    "name": "Al Ahqaf",
    "aya": 35,
    "english": "Winding Sand tracts",
    "turkish": "Ahkâf",
    "french": "Les dunes",
    "place": "Makkah",
    "arabic": "الأحقاف",
    "russian": "Барханы",
  },
  {
    "id": 47,
    "name": "Muhammad",
    "aya": 38,
    "english": "Muhammad",
    "turkish": "Muhammed",
    "french": "Muhammed",
    "place": "Madinah",
    "arabic": "محمد",
    "russian": "Мухаммад",
  },
  {
    "id": 48,
    "name": "Al Fath",
    "aya": 29,
    "english": "The Victory",
    "turkish": "Fetih",
    "french": "La victoire éclatante",
    "place": "Madinah",
    "arabic": "الفتح",
    "russian": "Победа",
  },
  {
    "id": 49,
    "name": "Al Hujurut",
    "aya": 18,
    "english": "The Private Apartments",
    "turkish": "Hucurât",
    "french": "Les appartements",
    "place": "Madinah",
    "arabic": "الحجرات",
    "russian": "Комнаты",
  },
  {
    "id": 50,
    "name": "Qaaf",
    "aya": 45,
    "english": "Q̈āf",
    "turkish": "Kâf",
    "french": "Q̈āf",
    "place": "Makkah",
    "arabic": "ق",
    "russian": "Каф",
  },
  {
    "id": 51,
    "name": "Ad Dariyat",
    "aya": 60,
    "english": "The Wind That Scatter",
    "turkish": "Zâriyât",
    "french": "Qui éparpillent",
    "place": "Makkah",
    "arabic": "الذاريات",
    "russian": "Рассеивающие прах",
  },
  {
    "id": 52,
    "name": "At Toor",
    "aya": 49,
    "english": "The Mount",
    "turkish": "Tûr",
    "french": "At-Tur",
    "place": "Makkah",
    "arabic": "الطور",
    "russian": "Гора",
  },
  {
    "id": 53,
    "name": "An Najm",
    "aya": 62,
    "english": "The Star",
    "turkish": "Necm",
    "french": "L'étoile",
    "place": "Makkah",
    "arabic": "النجم",
    "russian": "Звезда",
  },
  {
    "id": 54,
    "name": "Al Qamar",
    "aya": 55,
    "english": "The Moon",
    "turkish": "Kamer",
    "french": "La Lune",
    "place": "Makkah",
    "arabic": "القمر",
    "russian": "Месяц",
  },
  {
    "id": 55,
    "name": "Ar Rahman",
    "aya": 78,
    "english": "The Most Merciful",
    "turkish": "Rahmân",
    "french": "Le Tout Miséricordieux",
    "place": "Madinah",
    "arabic": "الرحمن",
    "russian": "Милостивый",
  },
  {
    "id": 56,
    "name": "Al Waqiah",
    "aya": 96,
    "english": "The Inevitable",
    "turkish": "Vâkıa",
    "french": "L'évenement",
    "place": "Makkah",
    "arabic": "الواقعة",
    "russian": "Событие",
  },
  {
    "id": 57,
    "name": "Al Hadeed",
    "aya": 29,
    "english": "The Iron",
    "turkish": "Hadîd",
    "french": "Le fer",
    "place": "Madinah",
    "arabic": "الحديد",
    "russian": "Железо",
  },
  {
    "id": 58,
    "name": "Al Mujadila",
    "aya": 22,
    "english": "The Pleading",
    "turkish": "Mücâdele",
    "french": "La discution",
    "place": "Madinah",
    "arabic": "المجادلة",
    "russian": "Препирающаяся",
  },
  {
    "id": 59,
    "name": "Al Hashr",
    "aya": 24,
    "english": "The Mustering",
    "turkish": "Haşr",
    "french": "L'exode",
    "place": "Madinah",
    "arabic": "الحشر",
    "russian": "Сбор",
  },
  {
    "id": 60,
    "name": "Al Mumtahanah",
    "aya": 13,
    "english": "The Examined One",
    "turkish": "Mümtehine",
    "french": "L'éprouvée",
    "place": "Madinah",
    "arabic": "الممتحنة",
    "russian": "Испытуемая",
  },
  {
    "id": 61,
    "name": "As Saff",
    "aya": 14,
    "english": "The Ranks",
    "turkish": "Saff",
    "french": "Le rang",
    "place": "Madinah",
    "arabic": "الصف",
    "russian": "Ряды",
  },
  {
    "id": 62,
    "name": "Al Jumu'ah",
    "aya": 11,
    "english": "Congregation (Friday)",
    "turkish": "Cuma",
    "french": "Le vendredi",
    "place": "Madinah",
    "arabic": "الجمعة",
    "russian": "Собрание",
  },
  {
    "id": 63,
    "name": "Al Munafiqoon",
    "aya": 11,
    "english": "The Hypocrites",
    "turkish": "Münâfikûn",
    "french": "Les hypocrites",
    "place": "Madinah",
    "arabic": "المنافقون",
    "russian": "Лицемеры",
  },
  {
    "id": 64,
    "name": "At Taghabun",
    "aya": 18,
    "english": "The Cheating",
    "turkish": "Tegâbün",
    "french": "La grande perte",
    "place": "Madinah",
    "arabic": "التغابن",
    "russian": "Взаимное обделение",
  },
  {
    "id": 65,
    "name": "At Talaq",
    "aya": 12,
    "english": "Divorce",
    "turkish": "Talâk",
    "french": "Le divorce",
    "place": "Madinah",
    "arabic": "الطلاق",
    "russian": "Развод",
  },
  {
    "id": 66,
    "name": "At Tahreem",
    "aya": 12,
    "english": "The Prohibition",
    "turkish": "Tahrîm",
    "french": "L'interdiction",
    "place": "Madinah",
    "arabic": "التحريم",
    "russian": "Запрещение",
  },
  {
    "id": 67,
    "name": "Al Mulk",
    "aya": 30,
    "english": "The Dominion",
    "turkish": "Mülk",
    "french": "La royauté",
    "place": "Makkah",
    "arabic": "الملك",
    "russian": "Власть",
  },
  {
    "id": 68,
    "name": "Al Qalam",
    "aya": 52,
    "english": "The Pen",
    "turkish": "Kalem",
    "french": "La plume",
    "place": "Makkah",
    "arabic": "القلم",
    "russian": "Письменная трость",
  },
  {
    "id": 69,
    "name": "Al Haaqqah",
    "aya": 52,
    "english": "The Sure Reality",
    "turkish": "Hâkka",
    "french": "Celle qui montre la vérité",
    "place": "Makkah",
    "arabic": "الحاقة",
    "russian": "Неминуемое",
  },
  {
    "id": 70,
    "name": "Al Ma'arij",
    "aya": 44,
    "english": "The Ways of Ascent",
    "turkish": "Meâric",
    "french": "Les voies d'ascension",
    "place": "Makkah",
    "arabic": "المعارج",
    "russian": "Ступени",
  },
  {
    "id": 71,
    "name": "Nooh",
    "aya": 28,
    "english": "Noah",
    "turkish": "Nûh",
    "french": "Noé",
    "place": "Makkah",
    "arabic": "نوح",
    "russian": "Ной",
  },
  {
    "id": 72,
    "name": "Al Jinn",
    "aya": 28,
    "english": "The Jinn",
    "turkish": "Cin",
    "french": "Les Djinns",
    "place": "Makkah",
    "arabic": "الجن",
    "russian": "Джинны",
  },
  {
    "id": 73,
    "name": "Al Muzammil",
    "aya": 20,
    "english": "The Enfolded One",
    "turkish": "Müzzemmil",
    "french": "L'enveloppé",
    "place": "Makkah",
    "arabic": "المزمل",
    "russian": "Закутавшийся",
  },
  {
    "id": 74,
    "name": "Al Muddathir",
    "aya": 56,
    "english": "The One Wrapped Up",
    "turkish": "Müddessir",
    "french": "Le revêtu d'un manteau",
    "place": "Makkah",
    "arabic": "المدثر",
    "russian": "Завернувшийся",
  },
  {
    "id": 75,
    "name": "Al Qiyamah",
    "aya": 40,
    "english": "Resurrection",
    "turkish": "Kıyâmet",
    "french": "La résurrection",
    "place": "Makkah",
    "arabic": "القيامة",
    "russian": "Воскресение",
  },
  {
    "id": 76,
    "name": "Al Insaan",
    "aya": 31,
    "english": "The Human",
    "turkish": "İnsân",
    "french": "L'homme",
    "place": "Madinah",
    "arabic": "الانسان",
    "russian": "Человек",
  },
  {
    "id": 77,
    "name": "Al Mursalat",
    "aya": 50,
    "english": "Those Sent Forth",
    "turkish": "Mürselât",
    "french": "Les envoyés",
    "place": "Makkah",
    "arabic": "المرسلات",
    "russian": "Посылаемые",
  },
  {
    "id": 78,
    "name": "An Naba",
    "aya": 40,
    "english": "The Great News",
    "turkish": "Nebe",
    "french": "La nouvelle",
    "place": "Makkah",
    "arabic": "النبأ",
    "russian": "Весть",
  },
  {
    "id": 79,
    "name": "An Naaziat",
    "aya": 46,
    "english": "Those Who Tear Out",
    "turkish": "Naziât",
    "french": "Les anges qui arrachent les âmes",
    "place": "Makkah",
    "arabic": "النازعات",
    "russian": "Исторгающие",
  },
  {
    "id": 80,
    "name": "Abasa",
    "aya": 42,
    "english": "He Frowned",
    "turkish": "Abese",
    "french": "Il s'est renfrogné",
    "place": "Makkah",
    "arabic": "عبس",
    "russian": "Нахмурился",
  },
  {
    "id": 81,
    "name": "At Takweer",
    "aya": 29,
    "english": "The Folding Up",
    "turkish": "Tekvîr",
    "french": "L'obscurcissement",
    "place": "Makkah",
    "arabic": "التكوير",
    "russian": "Скручивание",
  },
  {
    "id": 82,
    "name": "Al Infitar",
    "aya": 19,
    "english": "The Overthrowing",
    "turkish": "İnfitâr",
    "french": "La rupture",
    "place": "Makkah",
    "arabic": "الإنفطار",
    "russian": "Раскалывание",
  },
  {
    "id": 83,
    "name": "Al Mutaffifin",
    "aya": 36,
    "english": "The Cleaving Asunder",
    "turkish": "Mutaffifîn",
    "french": "Les fraudeurs",
    "place": "Makkah",
    "arabic": "المطففين",
    "russian": "Обвешивающие"
  },
  {
    "id": 84,
    "name": "Al Inshiqaaq",
    "aya": 25,
    "english": "The Dealers in Fraud",
    "turkish": "İnşikâk",
    "french": "La déchirure",
    "place": "Makkah",
    "arabic": "الإنشقاق",
    "russian": "Разверзнется"
  },
  {
    "id": 85,
    "name": "Al Burooj",
    "aya": 22,
    "english": "The Constellations",
    "turkish": "Burûc",
    "french": "Les constellations",
    "place": "Makkah",
    "arabic": "البروج",
    "russian": "Созвездия зодиака",
  },
  {
    "id": 86,
    "name": "At Taariq",
    "aya": 17,
    "english": "The Morning Star",
    "turkish": "Târık",
    "french": "L'astre nocturne",
    "place": "Makkah",
    "arabic": "الطارق",
    "russian": "Ночной путник",
  },
  {
    "id": 87,
    "name": "Al A'laa",
    "aya": 19,
    "english": "The Most High",
    "turkish": "A'lâ",
    "french": "Le Très-Haut",
    "place": "Makkah",
    "arabic": "الأعلى",
    "russian": "Всевышний",
  },
  {
    "id": 88,
    "name": "Al Ghaashiyah",
    "aya": 26,
    "english": "The Overwhelming Event",
    "turkish": "Gâşiye",
    "french": "L'enveloppante",
    "place": "Makkah",
    "arabic": "الغاشية",
    "russian": "Покрывающее",
  },
  {
    "id": 89,
    "name": "Al Fajr",
    "aya": 30,
    "english": "The Daybreak",
    "turkish": "Fecr",
    "french": "L'aube",
    "place": "Makkah",
    "arabic": "الفجر",
    "russian": "Заря",
  },
  {
    "id": 90,
    "name": "Al Balad",
    "aya": 20,
    "english": "The City",
    "turkish": "Beled",
    "french": "La cité",
    "place": "Makkah",
    "arabic": "البلد",
    "russian": "Город",
  },
  {
    "id": 91,
    "name": "Ash Shams",
    "aya": 15,
    "english": "The Sun",
    "turkish": "Şems",
    "french": "Le Soleil",
    "place": "Makkah",
    "arabic": "الشمس",
    "russian": "Солнце",
  },
  {
    "id": 92,
    "name": "Al Layl",
    "aya": 21,
    "english": "The Night",
    "turkish": "Leyl",
    "french": "La nuit",
    "place": "Makkah",
    "arabic": "الليل",
    "russian": "Ночь",
  },
  {
    "id": 93,
    "name": "Ad Dhuha",
    "aya": 11,
    "english": "The Glorious Morning Light",
    "turkish": "Duhâ",
    "french": "Le jour montant",
    "place": "Makkah",
    "arabic": "الضحى",
    "russian": "Утро",
  },
  {
    "id": 94,
    "name": "Ash Sharh",
    "aya": 8,
    "english": "The Opening Up of the Heart",
    "turkish": "İnşirâh",
    "french": "L'ouverture",
    "place": "Makkah",
    "arabic": "الشرح",
    "russian": "Раскрытие",
  },
  {
    "id": 95,
    "name": "At Teen",
    "aya": 8,
    "english": "The Fig Tree",
    "turkish": "Tîn",
    "french": "Le figuier",
    "place": "Makkah",
    "arabic": "التين",
    "russian": "Смоковница",
  },
  {
    "id": 96,
    "name": "Al Alaq",
    "aya": 19,
    "english": "The Clinging Clot",
    "turkish": "Alak",
    "french": "L'adhérence",
    "place": "Makkah",
    "arabic": "العلق",
    "russian": "Сгусток крови",
  },
  {
    "id": 97,
    "name": "Al Qadr",
    "aya": 5,
    "english": "The Night of Honor",
    "turkish": "Kadir",
    "french": "La destinée",
    "place": "Makkah",
    "arabic": "القدر",
    "russian": "Предопределение",
  },
  {
    "id": 98,
    "name": "Al Bayyinah",
    "aya": 8,
    "english": "The Clear Evidence",
    "turkish": "Beyyine",
    "french": "La preuve",
    "place": "Madinah",
    "arabic": "البينة",
    "russian": "Ясное знамение",
  },
  {
    "id": 99,
    "name": "Az Zalzalah",
    "aya": 8,
    "english": "The Earthquake",
    "turkish": "Zilzâl",
    "french": "La secousse",
    "place": "Madinah",
    "arabic": "الزلزلة",
    "russian": "Сотрясение",
  },
  {
    "id": 100,
    "name": "Al Aadiyaat",
    "aya": 11,
    "english": "The Courser",
    "turkish": "Âdiyât",
    "french": "Les coursiers",
    "place": "Makkah",
    "arabic": "العاديات",
    "russian": "Скачущие",
  },
  {
    "id": 101,
    "name": "Al Qaari'ah",
    "aya": 11,
    "english": "The Striking Hour",
    "turkish": "Kâria",
    "french": "Le fracas",
    "place": "Makkah",
    "arabic": "القارعة",
    "russian": "Великое бедствие",
  },
  {
    "id": 102,
    "name": "At Takaathur",
    "aya": 8,
    "english": "The Piling Up",
    "turkish": "Tekâsür",
    "french": "La course aux richesses",
    "place": "Makkah",
    "arabic": "التكاثر",
    "russian": "Страсть к приумножению",
  },
  {
    "id": 103,
    "name": "Al Asr",
    "aya": 3,
    "english": "The Time",
    "turkish": "Asr",
    "french": "Le temps",
    "place": "Makkah",
    "arabic": "العصر",
    "russian": "Время",
  },
  {
    "id": 104,
    "name": "Al Humazah",
    "aya": 9,
    "english": "The Scandalmonger",
    "turkish": "Hümeze",
    "french": "Les calomniateurs",
    "place": "Makkah",
    "arabic": "الهمزة",
    "russian": "Хулитель",
  },
  {
    "id": 105,
    "name": "Al Feel",
    "aya": 5,
    "english": "The Elephant",
    "turkish": "Fîl",
    "french": "L'éléphant",
    "place": "Makkah",
    "arabic": "الفيل",
    "russian": "Слон",
  },
  {
    "id": 106,
    "name": "Quraysh",
    "aya": 4,
    "english": "The Quraysh",
    "turkish": "Kureyş",
    "french": "Coraïsh",
    "place": "Makkah",
    "arabic": "قريش",
    "russian": "Курейшиты",
  },
  {
    "id": 107,
    "name": "Al Maa'oon",
    "aya": 7,
    "english": "The Neighbourly Assistance",
    "turkish": "Maûn",
    "french": "L'ustensile",
    "place": "Makkah",
    "arabic": "الماعون",
    "russian": "Мелочь",
  },
  {
    "id": 108,
    "name": "Al Kawthar",
    "aya": 3,
    "english": "Abundance",
    "turkish": "Kevser",
    "french": "l'abondance",
    "place": "Makkah",
    "arabic": "الكوثر",
    "russian": "Изобилие",
  },
  {
    "id": 109,
    "name": "Al Kaafiroon",
    "aya": 6,
    "english": "The Disbelievers",
    "turkish": "Kâfirûn",
    "french": "Les infidèles",
    "place": "Makkah",
    "arabic": "الكافرون",
    "russian": "Неверующие",
  },
  {
    "id": 110,
    "name": "An Nasr",
    "aya": 3,
    "english": "The Help",
    "turkish": "Nasr",
    "french": "Les secours",
    "place": "Madinah",
    "arabic": "النصر",
    "russian": "Помощь",
  },
  {
    "id": 111,
    "name": "Al Masad",
    "aya": 5,
    "english": "The Plaited Rope",
    "turkish": "Tebbet",
    "french": "Les fibres",
    "place": "Makkah",
    "arabic": "المسد",
    "russian": "Пальмовые волокна",
  },
  {
    "id": 112,
    "name": "Al Ikhlaas",
    "aya": 4,
    "english": "Purity of Faith",
    "turkish": "İhlâs",
    "french": "Le monothéisme pur",
    "place": "Makkah",
    "arabic": "الإخلاص",
    "russian": "Очищение веры",
  },
  {
    "id": 113,
    "name": "Al Falaq",
    "aya": 5,
    "english": "The Rising Dawn",
    "turkish": "Felak",
    "french": "L'aube naissante",
    "place": "Makkah",
    "arabic": "الفلق",
    "russian": "Рассвет",
  },
  {
    "id": 114,
    "name": "An Naas",
    "aya": 6,
    "english": "Mankind",
    "turkish": "Nâs",
    "french": "Les hommes",
    "place": "Makkah",
    "arabic": "الناس",
    "russian": "Люди",
  }
];
